### ISSUE TITLE
Reporte Architect

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-3-practica-architect-Luz1727#1]
[Reporte-Practica-LuzArlethLB.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Luz1727/files/12554059/Reporte-Practica-LuzArlethLB.pdf)

**Comment by yanet02** [comment]
Portada: 25 "Cumple con lo requerido"
Procedimiento: 25 muy bien
Figuras: 25 puntos BIEN HECHO
Resultados y conclusiones: 22 puntos Tiene conclusión, pero faltaron los resultados
Puntos totales: 97

Clasificación final: 19.4 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
